---
title: "Exercices"

---

# 

Exercices portant sur l’interrogation des données (Identification, filtrage, etc.)


::: {.partie .callout-note collapse="true" appearance="minimal"}

## Identification des entités et opérations archéologiques en Pays de la Loire

::: panel-tabset

## Données

Les données sont issues de l'Atlas du patrimoine.

## Fichiers


- Téléchargez le fichier zip "archéo-pdl-06-23" depuis Madoc. 

- Windows 10 : **Clic-droit\> Extraire tout** puis **exécutez** le fichier "archéo-pdl.qgz".

-  MacOs : **exécutez** le fichier "archéo-pdl.qgz".


:::{.callout-warning collapse=true appearance='default' icon=true}
## Bug d'affichage du fond de carte OpenStreetMap en salle informatique

En salle informatique, le fond de carte OpenStreetMap peut ne pas s'afficher. Pour régler le problème  procédez à un {{< kbd Ctrl-Alt-Suppr >}} puis sélectionnez **Se déconnecter** et recommencez...
:::


## Questions

Vous répondrez aux questions sur Madoc.

 

1. De quelle année date l'opération située au 2 Boulevard du Petit Port à Nantes (repère n°1) ?

-   année 2022.
-   année 2017.
-   année 2015.

<!-- 2022 -->



2. Quel type de vestige caractérise l'entité située au nord du camping du Petit Port à Nantes (repère n°2) ?

-   Voie.
-   Moulin.
-   Tumulus.

<!-- voie -->


3. De quelle année date l'opération située du 7 à 13, rue Saint Jean-Baptiste de la Salle à Nantes (repère n°3) ?

-   année 2022.
-   année 2017.
-   année 2015.

<!-- 2017 -->

4. De quelle période peut-être daté le manoir de l'Éperonnière mis à jour lors du chantier de la caserne Mellinet à Nantes (repère n°4) ?

-   Bas Moyen-âge - époque moderne.
-   Bas Moyen-âge - haut moyen-âge.
-   Haut moyen-âge - époque moderne.

<!-- -   Bas Moyen-âge - époque moderne. -->



5. Quels types de vestiges caractérisent les entités situées sur le campus Michelet Sciences (repère n°5) ? Veuillez choisir plusieurs réponses.

-   Voie
-   Blockaus.
-   Château non fortifié.
-   Moulin.
-   Muraille.

<!-- -   Blockaus. Château non fortifié. -->


6. Quels types de vestiges caractérisent les entités situées rue du Président de Gaulle à la Roche/Yon (repère n°6) ? Veuillez choisir plusieurs réponses.

-   Voie.
-   église.
-   Cimetière.
-   Moulin.
-   Muraille.


:::

:::


  


::: {.partie .callout-note collapse="true" appearance="minimal"}

##  Identification des sites antiques en Istrie

::: panel-tabset

## Données

Les données sont issues de la base Pleiades. 

## Fichiers


- Téléchargez le fichier zip "pleiades-07-23" depuis Madoc. 

- Windows 10 : **Clic-droit\> Extraire tout** puis **exécutez** le fichier "pleiades-06-23.qgz".

-  MacOs : **exécutez** le fichier "pleiades-07-23.qgz".


:::{.callout-warning collapse=true appearance='default' icon=true}
## Bug d'affichage du fond de carte OpenStreetMap en salle informatique

En salle informatique, le fond de carte OpenStreetMap peut ne pas s'afficher. Pour régler le problème  procédez à un {{< kbd Ctrl-Alt-Suppr >}} puis sélectionnez **Se déconnecter** et recommencez...
:::



## Questions

Vous répondrez aux questions sur Madoc.


1. Quel est le nom de cette cité romaine (repère n°1) ?
<!-- Pola -->

###### 

2. Pour quel empereur romain ce temple a-t-il été édifié (repère n°2) ? 
- Auguste.
- Tibère.
- Vespasien.

<!-- Auguste -->


3. De quel type de site antique s'agit-il (repère n°3) ? <!-- Arche -->
- Une arche.
- Un temple.
- Des thermes. 


4. De quel type de site antique s'agit-il (repère n°4) ? <!-- une villa -->

- Un temple.
- Une villa.
- Des thermes. 

5. Durant quelle période cet amphithéâtre fut-il construit (repère n°5) ? <!-- augustéenne Neron. -->

- De la période augustéenne et le règne de Neron.
- Du règne de Tibère à celui de Neron.
- Du règne de Vespasien à celui de Domitien.
:::
:::












